/obj/item/gun/ballistic/automatic/racket
	name = "R.A.C.Ket"
	desc = "An experimental automatic rifle chambered in 13x92"
	icon_state = "racket"
	w_class = WEIGHT_CLASS_NORMAL
	mag_type = /obj/item/ammo_box/magazine/mm1392
	can_suppress = FALSE
	burst_size = 4
	fire_delay = 3
	empty_indicator = TRUE
	empty_alarm = TRUE
	actions_types = list()
	bolt_type = BOLT_TYPE_STANDARD
	recoil = 0.2
	fire_sound = 'sound/weapons/gun/pistol/shot.ogg'
	dry_fire_sound = 'sound/weapons/gun/pistol/dry_fire.ogg'
	suppressed_sound = 'sound/weapons/gun/pistol/shot_suppressed.ogg'
	load_sound = 'sound/weapons/gun/pistol/mag_insert.ogg'
	load_empty_sound = 'sound/weapons/gun/pistol/mag_insert.ogg'
	eject_sound = 'sound/weapons/gun/pistol/mag_release.ogg'
	eject_empty_sound = 'sound/weapons/gun/pistol/mag_release.ogg'
	vary_fire_sound = FALSE
	rack_sound = 'sound/weapons/gun/pistol/rack_small.ogg'
	lock_back_sound = 'sound/weapons/gun/pistol/lock_small.ogg'
	bolt_drop_sound = 'sound/weapons/gun/pistol/drop_small.ogg'
	fire_sound_volume = 300
	bolt_wording = "bolt"